Refactor installation instructions according GCP latest UI
ofek/pypinfo pull request #149
Opened 2023-03-12 21:06 UTC by brunolnetto

The main caveats of this refactor are the step count increase, which we may work on to reduce.

2023-03-13 14:54 UTC, brunolnetto commented
The preview is available on repository https://github.com/alloyha/pypinfo

2023-03-14 07:15 UTC, hugovk requested changes
Thanks! Some minor proofreading suggestions.

2023-03-14 07:15 UTC, hugovk commented on README.md
> +6. A while after creation, at the left-top corner, select the project name of your choice on dropdown component AND at the left-top corner "Navigation Meny", select option on path 'Cloud Overview > D
```suggestion
6. A while after creation, at the left-top corner, select the project name of your choice on dropdown component AND at the left-top corner "Navigation Menu", select option "Cloud Overview > Dashboard":
```

2023-03-14 07:15 UTC, hugovk commented on README.md
> +**Remark**: You will be requested to go back to Big Query panel. In this case, click on top-left button "Navigation Menu", option "API and services > Enabled APIs and services" and on consequent page
```suggestion
**Note**: You will be requested to go back to Big Query panel. In this case, click on top-left button "Navigation Menu", option "API and services > Enabled APIs and services" and on consequent page, on item "Big Query API": 
```

2023-03-14 07:15 UTC, hugovk commented on README.md
> +14. On Big Query API panel (See **Remark** on item *10*), click on tab "CREDENTIALS". On section "Service accounts", click on created credentials on items 11, 12 and 13.
```suggestion
14. On Big Query API panel (See **Note** on item *10*), click on tab "CREDENTIALS". On section "Service accounts", click on created credentials on items 11, 12 and 13.
```

2023-03-14 07:15 UTC, hugovk commented on README.md
> +11. On page from "CREATE CREDENTIALS"-button click, choose the "BigQuery API", "Application Data" and "No, I'm not using them":
```suggestion
11. On the page after clicking the "CREATE CREDENTIALS" button, choose "BigQuery API", "Application Data" and "No, I'm not using them":
```

2023-03-14 07:15 UTC, hugovk commented on README.md
> +17. Run command `pip install pypinfo` on terminal
```suggestion
17. Run `python -m pip install pypinfo` in the terminal.
```

2023-03-14 11:16 UTC, brunolnetto commented
@hugovk  Done! 

Note: Have you seen this movie? https://www.youtube.com/watch?v=FG9rvNhdOX8

2023-03-14 12:00 UTC, hugovk approved these changes
Thanks!

I didn't double check the steps/screenshots actually match the Google Console, but otherwise looks good!

2023-03-14 12:00 UTC, hugovk commented
> @hugovk Done!
> 
> Note: Have you seen this movie? [youtube.com/watch?v=FG9rvNhdOX8](https://www.youtube.com/watch?v=FG9rvNhdOX8)

I have! :D

2023-03-14 12:40 UTC, brunolnetto commented
Well, well, well. I think we have a merging PR coming soon on my screen.

2023-06-01 13:57 UTC, merged